apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    com.docker.stack.expected-generation: "6"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-05-14T14:44:27Z"
  generation: 6
  labels:
    com.docker.service.id: ck8s-backend
    com.docker.service.name: backend
    com.docker.stack.namespace: ck8s
  name: backend
  namespace: ck8s-prod
  ownerReferences:
  - apiVersion: compose.docker.com/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: Stack
    name: ck8s
    uid: 690d98e4-95f1-11ea-96c4-025000000001
  resourceVersion: "75337"
  selfLink: /apis/extensions/v1beta1/namespaces/ck8s-prod/deployments/backend
  uid: f305a693-f822-4f76-bdc0-d6e8b7537c7a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      com.docker.service.id: ck8s-backend
      com.docker.service.name: backend
      com.docker.stack.namespace: ck8s
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        com.docker.service.id: ck8s-backend
        com.docker.service.name: backend
        com.docker.stack.namespace: ck8s
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - env:
        - name: CACHE_ENDPOINT_FILE
          value: /run/secrets/cache-endpoint
        - name: CACHE_PASSWORD_FILE
          value: /run/secrets/cache-password
        image: ezodude/backend-cok8s:prod
        imagePullPolicy: IfNotPresent
        name: backend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/secrets/cache-endpoint
          name: secret-0
          readOnly: true
          subPath: secret-0
        - mountPath: /run/secrets/cache-password
          name: secret-1
          readOnly: true
          subPath: secret-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secret-0
        secret:
          defaultMode: 420
          items:
          - key: file
            path: secret-0
          secretName: cache-endpoint
      - name: secret-1
        secret:
          defaultMode: 420
          items:
          - key: file
            path: secret-1
          secretName: cache-password
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-05-14T14:44:29Z"
    lastUpdateTime: "2020-05-14T14:44:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-14T14:44:27Z"
    lastUpdateTime: "2020-05-14T14:44:29Z"
    message: ReplicaSet "backend-85b99695" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
