apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-14T14:44:27Z"
  labels:
    com.docker.service.id: ck8s-frontend
    com.docker.service.name: frontend
    com.docker.stack.namespace: ck8s
  name: frontend
  namespace: ck8s-prod
  ownerReferences:
  - apiVersion: compose.docker.com/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: Stack
    name: ck8s
    uid: 690d98e4-95f1-11ea-96c4-025000000001
  resourceVersion: "75280"
  selfLink: /api/v1/namespaces/ck8s-prod/services/frontend
  uid: 4458408e-3b22-4f25-8330-fd8de3f07466
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    protocol: TCP
    targetPort: 55555
  selector:
    com.docker.service.id: ck8s-frontend
    com.docker.service.name: frontend
    com.docker.stack.namespace: ck8s
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
