apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    com.docker.stack.expected-generation: "1"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-05-14T14:44:27Z"
  generation: 1
  labels:
    com.docker.service.id: ck8s-frontend
    com.docker.service.name: frontend
    com.docker.stack.namespace: ck8s
  name: frontend
  namespace: ck8s-prod
  ownerReferences:
  - apiVersion: compose.docker.com/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: Stack
    name: ck8s
    uid: 690d98e4-95f1-11ea-96c4-025000000001
  resourceVersion: "75334"
  selfLink: /apis/extensions/v1beta1/namespaces/ck8s-prod/deployments/frontend
  uid: c33ba1ff-e091-4dea-b454-79aabfc09bc1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      com.docker.service.id: ck8s-frontend
      com.docker.service.name: frontend
      com.docker.stack.namespace: ck8s
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        com.docker.service.id: ck8s-frontend
        com.docker.service.name: frontend
        com.docker.stack.namespace: ck8s
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - env:
        - name: PORT
          value: "8080"
        image: ezodude/frontend-cok8s:prod
        imagePullPolicy: IfNotPresent
        name: frontend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-05-14T14:44:29Z"
    lastUpdateTime: "2020-05-14T14:44:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-14T14:44:27Z"
    lastUpdateTime: "2020-05-14T14:44:29Z"
    message: ReplicaSet "frontend-57d7fc6978" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
