version: '3.5'
services:
  frontend:
    image: ezodude/frontend-cok8s:prod
    build:
      context: .
      dockerfile: frontend.Dockerfile
    environment:
      PORT: 8080
    ports:
    - '80:8080'
    networks:
     - prod-esnet

  backend:
    image: ezodude/backend-cok8s:prod
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - prod.secrets
    secrets:
      - cache-endpoint
      - cache-password
    networks:
     - prod-esnet

networks:
  prod-esnet:
    driver: bridge

secrets:
  cache-endpoint:
    external: true
  cache-password:
    external: true