version: '3.5'
services:
  frontend:
    image: ezodude/frontend-cok8s:prod
    build:
      context: .
      dockerfile: frontend.Dockerfile
    environment:
      PORT: 8080
    ports:
    - '80:8080'
    networks:
     - prod-esnet

  # Deployment + Service
  backend:
    # Deployment: spec.template.spec.containers.image
    image: ezodude/backend-cok8s:prod

    # Deployment: spec.template.spec.containers.name
    container_name: backend

    # ignored
    build:
      context: .
      dockerfile: backend.Dockerfile

    # Deployment: matches spec.selector.matchLabels[]
    labels:
#      com.docker.service.id: "ck8s-backend"
#      com.docker.service.name: "backend"
#      com.docker.stack.namespace: "ck8s"

    # Deployment: default settings (missing in original)
    deploy:
      replicas: 1 # spec.replicas
      mode: replicated # default (replicated|global) enables using replicas
#      endpoint_mode: (vip=NodePort|dnsrr=N/A) ignored

    # Deployment: spec.template.spec.containers.env
    env_file:
      - prod.secrets # creates below
      # Deployment: spec.template.spec.containers.env[0].name
      # Deployment: spec.template.spec.containers.env[0].value
    secrets:
      - cache-endpoint
      - cache-password
    networks:
     - prod-esnet

networks:
  prod-esnet:
    driver: bridge

secrets:
  cache-endpoint:
    external: true
  cache-password:
    external: true