apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-13T16:25:42Z"
  labels:
    com.docker.service.id: ck8s-frontend
    com.docker.service.name: frontend
    com.docker.stack.namespace: ck8s
  name: frontend-published
  namespace: ck8s-prod
  ownerReferences:
  - apiVersion: compose.docker.com/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: Stack
    name: ck8s
    uid: 63811c31-9536-11ea-96c4-025000000001
  resourceVersion: "3415"
  selfLink: /api/v1/namespaces/ck8s-prod/services/frontend-published
  uid: ecd09cff-1af6-493d-9938-c7ccbf34a64c
spec:
  clusterIP: 10.100.101.58
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-tcp
    nodePort: 30231
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    com.docker.service.id: ck8s-frontend
    com.docker.service.name: frontend
    com.docker.stack.namespace: ck8s
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
