apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-13T16:25:42Z"
  labels:
    com.docker.service.id: ck8s-frontend
    com.docker.service.name: frontend
    com.docker.stack.namespace: ck8s
  name: frontend
  namespace: ck8s-prod
  ownerReferences:
  - apiVersion: compose.docker.com/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: Stack
    name: ck8s
    uid: 63811c31-9536-11ea-96c4-025000000001
  resourceVersion: "3404"
  selfLink: /api/v1/namespaces/ck8s-prod/services/frontend
  uid: cbbd9713-16e2-4cc2-8e2a-23a06a8813eb
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    protocol: TCP
    targetPort: 55555
  selector:
    com.docker.service.id: ck8s-frontend
    com.docker.service.name: frontend
    com.docker.stack.namespace: ck8s
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
