apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-15T11:22:09Z"
  labels:
    io.kompose.service: backend
  name: backend
  namespace: ck8s-kompose-prod
  resourceVersion: "1273"
  selfLink: /api/v1/namespaces/ck8s-kompose-prod/services/backend
  uid: 864ce544-6355-40a3-ad0a-7ecc5560119a
spec:
  clusterIP: 10.100.219.239
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
